VAR _SelectedAcYear = VALUES( Calendar[Academic Year] )
VAR _YEBudget =
    CALCULATE(
        SUM( Budgets[Value] ),
        REMOVEFILTERS( Calendar ),
        _SelectedAcYear
    )
VAR _Result =
    IF(
        ISFILTERED( 'Actual Description' ),
        BLANK( ),
        _YEBudget
    )
RETURN
    _Result