{
  "name": "Finance",
  "id": "139ae211-cd26-463a-8df7-9eb0f09c5d75",
  "compatibilityLevel": 1601,
  "model": {
    "name": "Finance",
    "description": "Analytics model using data from PSF.",
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": false,
      "returnErrorValuesAsNull": false
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Audit",
        "description": "Update times and dates.",
        "isHidden": true,
        "lineageTag": "2c649100-d086-47b5-a97d-afaf5360a96c",
        "columns": [
          {
            "name": "AuditId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "AuditId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "6fa899c2-67d4-478e-abc7-be19c085d539",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Data Source",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Data Source",
            "isAvailableInMdx": false,
            "lineageTag": "202421d5-d5d2-49fa-ad6d-6cc3c2bb3400",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Extraction Date Time",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Extraction Date Time",
            "formatString": "dd-mm-yyyy h:nn",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "54ef5f69-857c-4541-bba6-a6ce306a488a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Audit",
            "mode": "import",
            "queryGroup": "Conformed",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "  Nav = Source{[Schema = \"com\", Item = \"Dim_Audit\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "description": "Financial Calendar",
        "lineageTag": "950fef26-5681-42e2-9a74-16fa995e8b53",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "Date",
            "formatString": "dd/mm/yyyy",
            "encodingHint": "value",
            "lineageTag": "33280794-8620-47f5-91d2-58567a85b6a7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"D\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Academic Year",
            "dataType": "string",
            "sourceColumn": "Academic Year",
            "lineageTag": "94e49ed8-35da-4aff-ab58-c3f64bde37cf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Financial Period",
            "dataType": "int64",
            "sourceColumn": "Financial Period",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "4bc35d23-836c-4435-89f1-6e57d3261dbe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Financial Period & Year",
            "dataType": "string",
            "sourceColumn": "Financial Period & Year",
            "isAvailableInMdx": false,
            "lineageTag": "675dc983-e4ef-4f84-8ac3-1dc92beaa86d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Access Level",
            "dataType": "int64",
            "sourceColumn": "Access Level",
            "lineageTag": "be17875f-07ea-48c6-a2fa-c1b48d1c7354"
          },
          {
            "name": "Financial Year",
            "dataType": "string",
            "sourceColumn": "Financial Year",
            "lineageTag": "a17a5a05-e390-491c-9751-e96eae83289f"
          },
          {
            "name": "Period State",
            "dataType": "string",
            "sourceColumn": "Period State",
            "lineageTag": "860119bb-5c4c-41c1-9bbe-5aea63940540"
          },
          {
            "name": "End of Month",
            "dataType": "dateTime",
            "sourceColumn": "End of Month",
            "lineageTag": "c98c1046-ef9a-4c6c-bd67-423c7f2404c7"
          },
          {
            "name": "Period End Date",
            "dataType": "dateTime",
            "sourceColumn": "Period End Date",
            "lineageTag": "3fda4052-2135-405f-8676-d3e2f060ff86"
          },
          {
            "name": "PeriodOrder",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PeriodOrder",
            "lineageTag": "641a5ba1-2350-4e4b-b739-c705c1148caa"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "queryGroup": "Conformed",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"core-sys-dw01\"),",
                "    DB = Source{[Name=\"ALT-DW\"]}[Data],",
                "    SQL = Value.NativeQuery(",
                "            DB,",
                "            \"SELECT * FROM fin.vDim_FinancialCalendar\",",
                "            null,",
                "            [EnableFolding = true]",
                "  )",
                "in",
                "    SQL"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Period Label",
            "expression": [
              "VAR _MaxEndOfPeriod = FORMAT( MAX( 'Calendar'[Period End Date] ), \"DD MMMM yyyy\" )",
              "",
              "RETURN \"Correct as at \" & _MaxEndOfPeriod"
            ],
            "lineageTag": "3e8664ca-1686-4f5f-a3e4-90891be4fb14"
          }
        ]
      },
      {
        "name": "Account",
        "lineageTag": "2c3416f3-5d42-442b-b3f7-012da3d99622",
        "columns": [
          {
            "name": "AccountId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "AccountId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "aeafeea7-bf0f-4744-955c-a555c3bd024f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Account Name",
            "dataType": "string",
            "sourceColumn": "Account Name",
            "lineageTag": "df0bacac-75bf-43fe-a294-ad5fbfa22da9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Account Code",
            "dataType": "string",
            "sourceColumn": "Account Code",
            "lineageTag": "71733c7d-413b-4be7-a336-8321256b33bc",
            "summarizeBy": "none"
          },
          {
            "name": "AccountViewRole",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "AccountViewRole",
            "isAvailableInMdx": false,
            "lineageTag": "cf80efbe-0a06-4fd7-b82c-8f3595070dda",
            "summarizeBy": "none"
          },
          {
            "name": "Ledger Code",
            "dataType": "string",
            "sourceColumn": "Ledger Code",
            "lineageTag": "0d4aa346-85af-40eb-9b3a-76ff2bf90d58",
            "summarizeBy": "none"
          },
          {
            "name": "Ledger Name",
            "dataType": "string",
            "sourceColumn": "Ledger Name",
            "lineageTag": "2bfe755e-2bca-4cda-a01f-43986f6248e9",
            "summarizeBy": "none"
          },
          {
            "name": "Ledger Type",
            "dataType": "string",
            "sourceColumn": "Ledger Type",
            "lineageTag": "1b285830-56af-47d1-bd7a-2c6e8f157689",
            "summarizeBy": "none"
          },
          {
            "name": "LedgerViewRole",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LedgerViewRole",
            "isAvailableInMdx": false,
            "lineageTag": "d8a3dc0d-566c-4209-9cf3-31f318e93614",
            "summarizeBy": "none"
          },
          {
            "name": "Directorate",
            "dataType": "string",
            "sourceColumn": "Directorate",
            "lineageTag": "7c41a10e-ffc7-4e54-b5ca-b3dd60157516"
          }
        ],
        "partitions": [
          {
            "name": "Account",
            "mode": "import",
            "queryGroup": "Finance\\Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "  Nav = Source{[Schema = \"fin\", Item = \"Dim_Accounts\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "Nominal",
        "lineageTag": "bfea23ae-693e-4b02-b5b1-bdca5a0c7eed",
        "columns": [
          {
            "name": "NominalId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "NominalId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "d8b2c83c-538a-40a6-b80a-b511c4d41672",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Nominal Code",
            "dataType": "string",
            "sourceColumn": "Nominal Code",
            "lineageTag": "a51f775b-3c2f-437c-8abe-f1b53d10191e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Core Nominal Code",
            "dataType": "string",
            "sourceColumn": "Core Nominal Code",
            "lineageTag": "f6558a78-43a7-4391-85df-371c3959ad29",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Core Nominal",
            "dataType": "string",
            "sourceColumn": "Core Nominal",
            "sortByColumn": "Core Nominal Code",
            "lineageTag": "c4c082ca-0696-46bc-b18d-d3e903ad8fff",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Reporting Group Code",
            "dataType": "string",
            "sourceColumn": "Reporting Group Code",
            "displayFolder": "Management Account Sections",
            "lineageTag": "c3ed57d8-7f0d-4842-b213-1f42ffdadd45",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Reporting Group",
            "dataType": "string",
            "sourceColumn": "Reporting Group",
            "sortByColumn": "Reporting Group Code",
            "displayFolder": "Management Account Sections",
            "lineageTag": "6af5770a-542f-462c-a9d1-48b343b64096",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Reporting Group Section Code",
            "dataType": "string",
            "sourceColumn": "Reporting Group Section Code",
            "displayFolder": "Management Account Sections",
            "lineageTag": "47760dcb-fa87-46f5-96eb-8c3d2fb6167f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "CFR Code",
            "dataType": "string",
            "sourceColumn": "CFR Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "a7dca0e9-0f38-44f3-804a-0a4bd0fdc73a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "CFR Group",
            "dataType": "string",
            "sourceColumn": "CFR Group",
            "sortByColumn": "CFR Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "f9581769-54de-4100-93b0-9f9c4e7b05e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "SOFA Code",
            "dataType": "string",
            "sourceColumn": "SOFA Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "f9d4ed5c-8f0c-44a9-ac54-c7450e16dd93",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "SOFA Group",
            "dataType": "string",
            "sourceColumn": "SOFA Group",
            "sortByColumn": "SOFA Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "180a61ef-dab3-4b01-a5ff-6b758a2fd6e4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "DFE Chart of Accounts Code",
            "dataType": "string",
            "sourceColumn": "DFE Chart of Accounts Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "343efb55-b6fe-419f-9a1a-1f5aa60f9669",
            "summarizeBy": "none"
          },
          {
            "name": "DFE Chart of Accounts Group",
            "dataType": "string",
            "sourceColumn": "DFE Chart of Accounts Group",
            "sortByColumn": "DFE Chart of Accounts Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "22ffdb3a-e933-4392-933d-619e4b876c6a",
            "summarizeBy": "none"
          },
          {
            "name": "EFA Benchmark Return Code",
            "dataType": "string",
            "sourceColumn": "EFA Benchmark Return Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "8859d386-7e1e-48c8-aab0-b63c7e855c99",
            "summarizeBy": "none"
          },
          {
            "name": "EFA Benchmark Return Group",
            "dataType": "string",
            "sourceColumn": "EFA Benchmark Return Group",
            "sortByColumn": "EFA Benchmark Return Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "e1758c9f-165a-4d56-a514-7e5616e9c2fc",
            "summarizeBy": "none"
          },
          {
            "name": "EFA Budget Forecast Code",
            "dataType": "string",
            "sourceColumn": "EFA Budget Forecast Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "25200ab7-a233-4729-ae9d-1ac3eafb7842",
            "summarizeBy": "none"
          },
          {
            "name": "EFA Budget Forecast Group",
            "dataType": "string",
            "sourceColumn": "EFA Budget Forecast Group",
            "sortByColumn": "EFA Budget Forecast Code",
            "displayFolder": "Analysis Codes",
            "lineageTag": "7ccf2985-9647-40d2-a80d-51b3a229000a",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting Group Section",
            "dataType": "string",
            "sourceColumn": "Reporting Group Section",
            "sortByColumn": "Reporting Group Section Order",
            "displayFolder": "Management Account Sections",
            "lineageTag": "cb24b78d-9faf-485a-a49f-cee954d0fe05",
            "summarizeBy": "none"
          },
          {
            "name": "Display Multiplier",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Display Multiplier",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "eab0f648-815f-426b-a312-06e0d23a018c",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting Group Section Order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Reporting Group Section Order",
            "encodingHint": "value",
            "lineageTag": "9c6c510d-3a50-4cc7-ab38-526f9a635df5",
            "summarizeBy": "none"
          },
          {
            "name": "Include in Management Accounts?",
            "dataType": "string",
            "description": [
              "This flag is set at Reporting Group level (eg A0). It is manually set in:",
              "[ALT-DW].[fin].[Help_ReportingGroups]"
            ],
            "sourceColumn": "Include in Management Accounts?",
            "lineageTag": "fd2f8a07-0377-4767-a051-70284122d639",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Nominal",
            "mode": "import",
            "queryGroup": "Finance\\Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "  Nav = Source{[Schema = \"fin\", Item = \"Dim_Nominals\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "Actual Description",
        "description": "Line descriptions for each actual.",
        "lineageTag": "54bd01e6-0bd4-46a1-adf7-1fc25d703c81",
        "columns": [
          {
            "name": "Actual Description",
            "dataType": "string",
            "sourceColumn": "Actual Description",
            "lineageTag": "84e3f100-9e28-4840-88e5-6b95af831a56",
            "summarizeBy": "none"
          },
          {
            "name": "ActualDescriptionId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "ActualDescriptionId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "aca0163a-74db-43e8-9371-51a3126b0ff5",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Actual Description",
            "mode": "import",
            "queryGroup": "Finance\\Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "  Nav = Source{[Schema = \"fin\", Item = \"Dim_ActualDescriptions\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "Budgets",
        "description": [
          "Budget data from PSF. ",
          "Only pulls through budget infromation for codes which don't contain FC or FOR."
        ],
        "lineageTag": "02cbf1d4-8cd4-475a-a64e-8897cb2692f1",
        "columns": [
          {
            "name": "NominalId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "8243b178-40fb-4cd6-8c69-c2153fd0bb1e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "AccountId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "4b77b769-0f70-4f9d-8bb7-0709b66b7227",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "BudgetNameId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BudgetNameId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "f70c70c3-c921-4135-be7f-77d7fac4152e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Period End Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Period End Date",
            "formatString": "Long Date",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "7641644d-476c-445e-89be-cbb61c205110",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"D\" /></DateTimes></Format>"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "AuditId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AuditId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "08e6824e-25b3-4814-b56c-b01ccb8eb5fe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Value",
            "formatString": "#,##0.00",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "1fa7806b-ecbe-4265-975f-f35ac3a21c9d",
            "summarizeBy": "none"
          },
          {
            "name": "SecurityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SecurityId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "a2731148-f6bf-4cc3-b738-95b3df24a6c8"
          },
          {
            "name": "AccountLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountLocationId",
            "lineageTag": "2f8a8408-1a76-4a4f-ba91-89d8370e57ae"
          },
          {
            "name": "NominalLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalLocationId",
            "lineageTag": "2c6c431f-a432-45d9-b0d5-0bd3872435dd"
          }
        ],
        "partitions": [
          {
            "name": "Budgets",
            "mode": "import",
            "queryGroup": "Finance\\Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"core-sys-dw01\"),",
                "    DB = Source{[Name=\"ALT-DW\"]}[Data],",
                "    SQL = Value.NativeQuery(",
                "            DB,",
                "            \"SELECT",
                "                b.NominalLocationId,",
                "                b.AccountLocationId,",
                "                b.NominalId,",
                "                b.AccountId,",
                "                b.BudgetNameId,",
                "                b.[Period End Date],",
                "                b.SecurityId,",
                "                b.AuditId,",
                "                b.[Value]",
                "            FROM fin.Fact_Budgets AS b",
                "            INNER JOIN fin.Dim_BudgetNames AS n ON b.BudgetNameId = n.BudgetNameId ",
                "            WHERE NOT (n.[Budget Code] LIKE '%FC%'",
                "                OR n.[Budget Code] LIKE '%FOR%')\" ,",
                "            null,",
                "            [EnableFolding = true]",
                "  )",
                "in",
                "    SQL"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Budget",
            "description": [
              "Sum of budget values from PSF. ",
              "(Not division of year end)"
            ],
            "expression": [
              "VAR _Budget = SUM( Budgets[Value] )",
              "",
              "VAR _BudgetDisplay =",
              "    IF(",
              "        ISFILTERED( 'Actual Description' ) || ISFILTERED ( XAccount ),",
              "        BLANK( ),",
              "        _Budget",
              "    )",
              "",
              "RETURN _BudgetDisplay"
            ],
            "formatString": "#,##0.00",
            "lineageTag": "e1f3526b-59a8-4aa7-b353-44b9a29eaa40"
          },
          {
            "name": "YTD Budget",
            "description": "YE Budget with a simple 1/12th scaling per month applied.",
            "expression": [
              "VAR _LatestVisibleMonthEnd = MAX( Calendar[End of Month] )",
              "VAR _LatestVisibleFY = MAX ( Calendar[Financial Year] )",
              "VAR _VisibleMonths = ",
              "    CALCULATE(",
              "        DISTINCTCOUNT( Calendar[End of Month] ),",
              "        REMOVEFILTERS ( Calendar ),",
              "        Calendar[Financial Year] = _LatestVisibleFY,",
              "        Calendar[End of Month] <= _LatestVisibleMonthEnd",
              "    )",
              "",
              "",
              "VAR _YTDBudget = ",
              "    DIVIDE( [YE Budget] * _VisibleMonths, 12 )",
              "    ",
              "RETURN",
              "    _YTDBudget"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "e91f5276-4a88-44c8-86e0-9d0f49d51a4c"
          },
          {
            "name": "YE Budget",
            "expression": [
              "VAR _SelectedAcYear = VALUES( Calendar[Academic Year] )",
              "VAR _YEBudget =",
              "    CALCULATE(",
              "        SUM( Budgets[Value] ),",
              "        REMOVEFILTERS( Calendar ),",
              "        _SelectedAcYear",
              "    )",
              "VAR _Result =",
              "    IF(",
              "        ISFILTERED( 'Actual Description' ),",
              "        BLANK( ),",
              "        _YEBudget",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "ebc4b4f2-9d01-4706-9dc4-396707143268"
          },
          {
            "name": "Budgets Exist",
            "expression": "INT( NOT ( ISEMPTY( 'Budgets' ) ) )",
            "formatString": "#,##0",
            "displayFolder": "Slicer Filters",
            "lineageTag": "fad97f10-d26a-4e43-8908-293b50011171"
          }
        ]
      },
      {
        "name": "Actuals",
        "description": "Actuals data from PSF.",
        "lineageTag": "329b565b-f615-4eb4-ab31-f7aa4a5ad8ce",
        "columns": [
          {
            "name": "NominalId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "9e9c716c-ef2f-44f6-a55b-ab5934a4d20b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "AccountId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "3cb6385a-63a5-485f-a128-e41c42c93a95",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "PeriodEndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "PeriodEndDate",
            "formatString": "dd/mm/yyyy",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "e86c8acc-1f94-4e24-86a7-f6602f083ea6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"2057\" Group=\"LongDate\" FormatString=\"D\" /></DateTimes></Format>"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "AuditId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AuditId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "196a0925-cd9d-4d67-83d2-2d9ea2f6db7e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Value",
            "formatString": "#,##0.00",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "d1c2689d-ac38-4581-a0d5-f02ce24f468b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Discount",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "00e58293-2621-4559-94e7-f88bb091afb7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "DocumentId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DocumentId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "a02b24ca-a479-4d88-8ffb-b29b1a5c61eb",
            "summarizeBy": "none"
          },
          {
            "name": "ActualDescriptionId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ActualDescriptionId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "9358806a-3c04-499e-be70-3c873718a197",
            "summarizeBy": "none"
          },
          {
            "name": "XAccountId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "XAccountId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "446eed6a-7c0f-4ead-bebc-9ceee3f4eaee",
            "summarizeBy": "none"
          },
          {
            "name": "SecurityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SecurityId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "712cce35-55d8-485f-bc0c-b2ecb51a39bc",
            "summarizeBy": "none"
          },
          {
            "name": "ActualStatusId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ActualStatusId",
            "lineageTag": "513c7180-ff67-440a-8f2e-f49a82d56bb9"
          },
          {
            "name": "DocumentDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DocumentDate",
            "lineageTag": "053007f5-8c64-4043-b3ef-d21ae3afb827"
          },
          {
            "name": "AgedDocumentId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AgedDocumentId",
            "lineageTag": "a62efe8e-3b10-45e9-b727-809f098348a6"
          },
          {
            "name": "AccountLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountLocationId",
            "lineageTag": "b702ec39-e7d5-49ed-a6a5-81635a5eabcc"
          },
          {
            "name": "NominalLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalLocationId",
            "lineageTag": "f7f65d19-b0d0-4980-be04-abcddc7267e6"
          },
          {
            "name": "RefNo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RefNo",
            "lineageTag": "232d48bf-c4b9-4348-a513-621e77ad367f"
          },
          {
            "name": "ReqDocDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ReqDocDate",
            "lineageTag": "77c9b4a5-f804-485a-bcc9-9f8854206608"
          },
          {
            "name": "ReqDocNo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ReqDocNo",
            "lineageTag": "583e715a-9cd3-405b-baf9-f9737a8aa054"
          },
          {
            "name": "ReqToPoinDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ReqToPoinDays",
            "lineageTag": "efa242ef-bc63-484f-95f0-0893b361716a"
          },
          {
            "name": "GRNDocDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "GRNDocDate",
            "lineageTag": "8a9df029-2909-432f-84bd-6c492e9b7e11"
          },
          {
            "name": "GRNDocNo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GRNDocNo",
            "lineageTag": "67cc0d7b-6c89-4756-9d44-862fc60521df"
          },
          {
            "name": "GRNtoPoinDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GRNtoPoinDays",
            "lineageTag": "50d39322-5e6b-4855-b42f-08895a2fb5b2"
          }
        ],
        "partitions": [
          {
            "name": "Actuals",
            "mode": "import",
            "queryGroup": "Finance\\Facts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "    Nav = Source{[Schema = \"fin\", Item = \"Fact_Actuals\"]}[Data],",
                "    RemoveCol = Table.RemoveColumns(Nav, {\"ActualId\", \"FinancialPeriodId\"})",
                "in",
                "  RemoveCol"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Actual",
            "description": "Sum of actual values from PSF.",
            "expression": [
              "SUM( Actuals[Value] )",
              ""
            ],
            "formatString": "#,##0.00",
            "lineageTag": "24cf0026-2b09-4148-8135-dd8fae68216c"
          },
          {
            "name": "Actuals Exist",
            "expression": "INT( NOT ( ISEMPTY( Actuals ) ) )",
            "formatString": "#,##0",
            "displayFolder": "Slicer Filters",
            "lineageTag": "717aba0c-d029-4891-97ce-5def5b3c8931",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"DisplayFolder\"]"
              }
            ]
          },
          {
            "name": "YTD Actual",
            "expression": [
              "CALCULATE( ",
              "    [Actual], ",
              "    DATESYTD( Calendar[Date], \"31-Aug\" )",
              ")",
              ""
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "33822ff2-35ce-4ebb-9cd8-f9ce2ae1b8af"
          },
          {
            "name": "YTD Variance",
            "expression": [
              "[YTD Budget] - [YTD Actual]",
              ""
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "0bfdde47-9b01-46d0-bc6c-416e4e5cebbb"
          },
          {
            "name": "Variance",
            "description": "Actual Variance from Budget",
            "expression": [
              "[Budget] - [Actual]",
              "",
              "//Expenture Variances (Budget – Actual) ",
              "//Postitive variance as positive ",
              "//Negative variance as negatives ",
              "//",
              "//Income Variances (Budget – Actual) ",
              "//Negative variance as positive ",
              "//Positive variance as negative "
            ],
            "formatString": "#,##0.00",
            "lineageTag": "8eba4722-3422-41fa-adc7-1209b8868158"
          },
          {
            "name": "YTD % Variance",
            "expression": [
              "VAR _VarianceFromBudget = [YTD Variance]",
              "VAR _YTDBudget = [YTD Budget]",
              "//VAR _Mult = SELECTEDVALUE( Nominal[Display Multiplier], -1 )",
              "VAR _Result = DIVIDE( _VarianceFromBudget, _YTDBudget )",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,##0.0 %",
            "displayFolder": "Time Intelligence",
            "lineageTag": "ee849868-c12e-4000-93b9-c01af57dd7eb"
          },
          {
            "name": "Actuals and Budgets Exist",
            "expression": "INT( NOT ( ISEMPTY( Actuals ) && ISEMPTY( Budgets ) ) )",
            "formatString": "#,##0",
            "displayFolder": "Slicer Filters",
            "lineageTag": "04b46bd1-031d-441e-b981-1923459c637e"
          },
          {
            "name": "Zero Test",
            "description": [
              "Removes all filters except for date related ones.",
              "Checks for sum to zero."
            ],
            "expression": [
              "CALCULATE (",
              "    [Actual],",
              "    REMOVEFILTERS(),",
              "    VALUES ( Calendar[Date])",
              ")"
            ],
            "formatString": "#,##0.00",
            "lineageTag": "0b3396a2-34c3-4e9d-9da5-6fbe8c0cf571"
          },
          {
            "name": "Extraction Time",
            "expression": [
              "CALCULATE(",
              "    MAX( Audit[Extraction Date Time] ),",
              "    TREATAS( DISTINCT( Actuals[AuditId] ), Audit[AuditId] )",
              ")",
              ""
            ],
            "formatString": "dd-mm-yyyy hh:nn",
            "lineageTag": "7ea11408-9efc-46a9-aabf-763b838ffa55"
          },
          {
            "name": "Left to Spend",
            "expression": [
              "VAR _Commitment =  ",
              "    CALCULATE(",
              "        [Commitment],",
              "        REMOVEFILTERS ( Calendar ),",
              "        VALUES ( Calendar[Academic Year] )",
              "    )",
              "",
              "VAR _Variance = [YE Budget] - ( [YTD Actual] + _Commitment )",
              "VAR _Result = ",
              "    IF(",
              "        ISBLANK( [YE Budget] ),",
              "        BLANK(),",
              "        _Variance",
              "        ",
              "    )",
              "RETURN _Result"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "3801ad86-9872-4e97-ac89-54a7a60c9870"
          },
          {
            "name": "% Spend of YE Budget",
            "expression": [
              "VAR _Result = ",
              "    DIVIDE(",
              "        [YTD Actual],",
              "        [YE Budget]",
              "    )",
              "    ",
              "RETURN _Result"
            ],
            "formatString": "#,##0.0 %",
            "displayFolder": "Time Intelligence",
            "lineageTag": "223ac8b5-70a9-4bd5-8f45-2f51862d8be9"
          },
          {
            "name": "% of POINS with Later REQs",
            "expression": [
              "VAR _tblDocs = ",
              "CALCULATETABLE(",
              "    SUMMARIZE(",
              "        Actuals,",
              "        Actuals[DocumentId],",
              "        Actuals[ReqDocDate],",
              "        Actuals[DocumentDate]",
              "    ),",
              "    NOT ( ISBLANK( Actuals[ReqDocDate] ) )",
              ")",
              "",
              "VAR _NumDocs = COUNTROWS ( _tblDocs )",
              "VAR _NumLate = ",
              "    COUNTROWS(",
              "        FILTER(",
              "            _tblDocs,",
              "            Actuals[ReqDocDate] > Actuals[DocumentDate]",
              "        )",
              "    )",
              "    ",
              "VAR _Result = DIVIDE (_NumLate, _NumDocs)",
              "",
              "RETURN _Result"
            ],
            "formatString": "#,##0.0 %",
            "displayFolder": "Team Metrics",
            "lineageTag": "aa21eb5e-10f8-4529-a0d9-f218c82393d8"
          },
          {
            "name": "% of GRN Over 10 Days After POIN",
            "expression": [
              "VAR _tblDocs = ",
              "CALCULATETABLE(",
              "    SUMMARIZE(",
              "        Actuals,",
              "        Actuals[DocumentId],",
              "        Actuals[GRNDocDate],",
              "        Actuals[DocumentDate]",
              "    ),",
              "    NOT ( ISBLANK( Actuals[GRNDocDate] ) )",
              ")",
              "",
              "VAR _NumDocs = COUNTROWS ( _tblDocs )",
              "VAR _NumLate = ",
              "    COUNTROWS(",
              "        FILTER(",
              "            _tblDocs,",
              "            Actuals[GRNDocDate] - Actuals[DocumentDate] > 10",
              "        )",
              "    )",
              "    ",
              "VAR _Result = DIVIDE (_NumLate, _NumDocs)",
              "",
              "RETURN _Result"
            ],
            "formatString": "#,##0.0 %",
            "displayFolder": "Team Metrics",
            "lineageTag": "edc4aaa6-3295-4234-a540-e044509c2039"
          },
          {
            "name": "YTD Actual Per Student",
            "expression": [
              "DIVIDE (",
              "    [YTD Actual],",
              "    [# Students]",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "CLFP",
            "lineageTag": "6b478edb-aee3-4061-99bd-1b2e9808e129"
          }
        ]
      },
      {
        "name": "Budget Name",
        "lineageTag": "dd0ae372-3744-492b-971c-d02d7327eab1",
        "columns": [
          {
            "name": "BudgetNameId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "BudgetNameId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "4cfade83-12cd-4090-9823-f52a20e5e6cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Budget Code",
            "dataType": "string",
            "sourceColumn": "Budget Code",
            "lineageTag": "8524110a-4379-41f0-9a1b-5cfadbec9bcb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Budget Title",
            "dataType": "string",
            "sourceColumn": "Budget Title",
            "lineageTag": "e11cb64a-9e34-43d0-b0ef-24c4cb6835d7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Budget Name",
            "mode": "import",
            "queryGroup": "Finance\\Dimensions",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"core-sys-dw01\"),",
                "    DB = Source{[Name=\"ALT-DW\"]}[Data],",
                "    SQL = Value.NativeQuery(",
                "            DB,",
                "            \"SELECT",
                "\t            n.BudgetNameId,",
                "\t            n.[Budget Code],",
                "                n.[Budget Title]",
                "            FROM fin.Dim_BudgetNames AS n",
                "            WHERE NOT (n.[Budget Code] LIKE '%FC%'",
                "                OR n.[Budget Code] LIKE '%FOR%')\",",
                "            null,",
                "            [EnableFolding = true]",
                "  )",
                "in",
                "    SQL"
              ]
            }
          }
        ]
      },
      {
        "name": "PSF User",
        "isHidden": true,
        "lineageTag": "9c5cde88-8430-455b-b30b-e51e72c2c54d",
        "columns": [
          {
            "name": "Active",
            "dataType": "boolean",
            "sourceColumn": "Active",
            "lineageTag": "67f21b3e-5ffb-457a-9ffc-acb35f0e5689",
            "summarizeBy": "none"
          },
          {
            "name": "Account Inf PersonId",
            "dataType": "int64",
            "sourceColumn": "Account Inf PersonId",
            "encodingHint": "value",
            "lineageTag": "335db69b-3b04-4a20-b4e7-a5cf338b15b7",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email",
            "lineageTag": "81b636ae-aff2-4597-a151-a555f8c470f9",
            "summarizeBy": "none"
          },
          {
            "name": "Employee No",
            "dataType": "string",
            "sourceColumn": "Employee No",
            "lineageTag": "fbaafc90-e213-463d-ba9a-cc8044aa754d",
            "summarizeBy": "none"
          },
          {
            "name": "Latest PSF Use",
            "dataType": "dateTime",
            "sourceColumn": "Latest PSF Use",
            "formatString": "dd/mm/yyyy",
            "encodingHint": "value",
            "lineageTag": "d483281b-10b1-4c67-95c2-7707b2fa38b2",
            "summarizeBy": "none"
          },
          {
            "name": "Leaving Date",
            "dataType": "dateTime",
            "sourceColumn": "Leaving Date",
            "formatString": "dd/mm/yyyy",
            "encodingHint": "value",
            "lineageTag": "5952763d-376b-4070-8d59-0f1dab1bfdc8",
            "summarizeBy": "none"
          },
          {
            "name": "Office 365 Email",
            "dataType": "string",
            "sourceColumn": "Office 365 Email",
            "lineageTag": "e49db81a-6c13-4c86-942b-5435a73ff62d",
            "summarizeBy": "none"
          },
          {
            "name": "Old Account No PersonId",
            "dataType": "boolean",
            "sourceColumn": "Old Account No PersonId",
            "lineageTag": "9a18262e-f21e-402a-ab08-8dc5a7cfd252",
            "summarizeBy": "none"
          },
          {
            "name": "PSF User Name",
            "dataType": "string",
            "sourceColumn": "PSF User Name",
            "lineageTag": "5f4b09d2-a9b7-4bce-a266-3df677a20a60",
            "summarizeBy": "none"
          },
          {
            "name": "PSFUserId",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "PSFUserId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "935c25c1-f556-4d41-82e9-83dcc429fcff",
            "summarizeBy": "none"
          },
          {
            "name": "Static Account",
            "dataType": "boolean",
            "sourceColumn": "Static Account",
            "lineageTag": "2e74108c-3fa3-498a-bde2-1b4d8ad2cbfd",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "PSF User",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "  Nav = Source{[Schema = \"fin\", Item = \"Dim_PSFUsers\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Number of Active Users",
            "expression": [
              "COUNTROWS ( 'PSF User' )",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "cddefa1c-282e-412c-89a8-147bea5d6657"
          },
          {
            "name": "User Slicer Filter",
            "expression": "INT ( NOT ( ISEMPTY ( 'PSF User') ) )",
            "formatString": "#,##0",
            "lineageTag": "da0b3e46-a311-45f5-b692-235152bee544"
          },
          {
            "name": "Number of Users Who Have More Recent Activity",
            "expression": [
              "VAR MaxVisibleDate = MAX ( 'Calendar'[Date] )",
              "RETURN",
              "    CALCULATE (",
              "        COUNTROWS ( 'PSF User' ),",
              "        'Calendar'[Date] >= MaxVisibleDate",
              "    )"
            ],
            "formatString": "#,##0",
            "lineageTag": "b3e99169-3d0b-4bf2-8fe6-e7a1521ed454"
          }
        ]
      },
      {
        "name": "Document",
        "description": "Details for each document.",
        "lineageTag": "0f992545-b4d7-4c10-8b66-670a772c368f",
        "columns": [
          {
            "name": "Created By",
            "dataType": "string",
            "sourceColumn": "Created By",
            "lineageTag": "2ac6752c-4361-42a6-bf28-936e05047ce2",
            "summarizeBy": "none"
          },
          {
            "name": "Document Number",
            "dataType": "int64",
            "sourceColumn": "Document Number",
            "encodingHint": "value",
            "lineageTag": "b342d1e4-12cc-466f-9f9d-2cd5e80db6a1",
            "summarizeBy": "none"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "sourceColumn": "Document Type",
            "lineageTag": "813faf24-6573-47d7-8df2-20e25912c15a",
            "summarizeBy": "none"
          },
          {
            "name": "Document Type Code",
            "dataType": "string",
            "sourceColumn": "Document Type Code",
            "lineageTag": "1822ea26-cbce-4f87-bcf1-a416dbfb53e0",
            "summarizeBy": "none"
          },
          {
            "name": "DocumentId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "DocumentId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "86a79edb-4ebc-4215-b018-466684c7ba7d",
            "summarizeBy": "none"
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "sourceColumn": "Document Date",
            "formatString": "dd/mm/yyyy",
            "encodingHint": "value",
            "lineageTag": "d6113265-db9b-4308-aa0c-64174db25d62",
            "summarizeBy": "none"
          },
          {
            "name": "Input Date",
            "dataType": "dateTime",
            "sourceColumn": "Input Date",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "cee2f692-57b6-4e03-bd82-aab397efe1c0"
          }
        ],
        "partitions": [
          {
            "name": "Document",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "  Nav = Source{[Schema = \"fin\", Item = \"Dim_Documents\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "Forecast Name",
        "lineageTag": "06cd1edc-9826-4f38-ad58-3eb3ddd07d82",
        "columns": [
          {
            "name": "Forecast Code",
            "dataType": "string",
            "sourceColumn": "Forecast Code",
            "lineageTag": "75a41baa-179b-4426-833b-ade8b300f5b3"
          },
          {
            "name": "Forecast Title",
            "dataType": "string",
            "sourceColumn": "Forecast Title",
            "lineageTag": "8555683b-8016-4cdf-9418-41e4e8874cc8"
          },
          {
            "name": "ForecastNameId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "ForecastNameId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "7b92cebd-9748-496f-b766-60cfa3f2ff2d",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Forecast Name",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"core-sys-dw01\"),",
                "    DB = Source{[Name=\"ALT-DW\"]}[Data],",
                "    SQL = Value.NativeQuery(",
                "            DB,",
                "            \"SELECT",
                "                n.BudgetNameId AS [ForecastNameId],",
                "                n.[Budget Code] AS [Forecast Code],",
                "                n.[Budget Title] AS [Forecast Title]",
                "            FROM fin.Dim_BudgetNames AS n",
                "            WHERE n.[Budget Code] LIKE '%FC%' ",
                "                OR n.[Budget Code] LIKE '%FOR%'\",",
                "            null,",
                "            [EnableFolding = true]",
                "  )",
                "in",
                "    SQL"
              ]
            }
          }
        ]
      },
      {
        "name": "Forecasts",
        "description": [
          "Forecast data from PSF. ",
          "Only pulls through those that have codes containing FC or FOR.",
          ""
        ],
        "lineageTag": "d3bff017-a86a-4600-ade0-dea4d31ec5cf",
        "columns": [
          {
            "name": "AccountId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "b8d4b7e6-079c-4e42-b159-ceb83f6e753a",
            "summarizeBy": "none"
          },
          {
            "name": "AuditId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AuditId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "00112b6e-1d59-44df-8664-a65013017b83",
            "summarizeBy": "none"
          },
          {
            "name": "ForcastNameId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ForcastNameId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "52e6f143-b946-4246-b926-8743230950bd",
            "summarizeBy": "none"
          },
          {
            "name": "NominalId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "59b85f53-a70e-4dd4-8058-5d472564cb26",
            "summarizeBy": "none"
          },
          {
            "name": "Period End Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Period End Date",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "00be4c86-cc6f-409b-97ee-d32df7ce0174",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Value",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "92d5cb94-4050-4aee-9c30-65c262e7ec36",
            "summarizeBy": "none"
          },
          {
            "name": "SecurityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SecurityId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "f2eefac5-8a30-4ae7-a045-a10224d2e6ed"
          },
          {
            "name": "AccountLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountLocationId",
            "lineageTag": "a1463831-9cd5-4d42-9a4b-603df367cd45"
          },
          {
            "name": "NominalLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalLocationId",
            "lineageTag": "778cb627-1519-4e91-b686-5c49b74cc32f"
          }
        ],
        "partitions": [
          {
            "name": "Forecasts",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Databases(\"core-sys-dw01\"),",
                "    DB = Source{[Name=\"ALT-DW\"]}[Data],",
                "    SQL = Value.NativeQuery(",
                "            DB,",
                "            \"SELECT",
                "                b.NominalLocationId,",
                "                b.AccountLocationId,",
                "                b.NominalId,",
                "                b.AccountId,",
                "                b.BudgetNameId AS [ForcastNameId],",
                "                b.[Period End Date],",
                "                b.SecurityId,",
                "                b.AuditId,",
                "                b.[Value]",
                "            FROM fin.Fact_Budgets AS b",
                "            INNER JOIN fin.Dim_BudgetNames AS n ON b.BudgetNameId = n.BudgetNameId ",
                "            WHERE n.[Budget Code] LIKE '%FC%'",
                "                OR n.[Budget Code] LIKE '%FOR%'\",",
                "            null,",
                "            [EnableFolding = true]",
                "  )",
                "in",
                "    SQL"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Forecast",
            "description": "Sum of forecast values from PSF.",
            "expression": [
              "//VAR _DisplayMult = SELECTEDVALUE ( Nominal[Display Multiplier], -1)",
              "VAR _Forecast = SUM( Forecasts[Value] ) ",
              "VAR _ForecastDisplay =",
              "    IF(",
              "        ISFILTERED( 'Actual Description' ) || ISFILTERED ( XAccount ),",
              "        BLANK( ),",
              "        _Forecast",
              "    )",
              "VAR _Result = _ForecastDisplay",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,##0.00",
            "lineageTag": "789735d8-1977-42f8-90e9-045f22353ebe"
          },
          {
            "name": "YTD Forecast",
            "expression": [
              "VAR _YTDForecast =",
              "    CALCULATE(",
              "        [Forecast],",
              "        DATESYTD( Calendar[Date], \"31-Aug\" )",
              "    )",
              "VAR _Result = _YTDForecast",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "b7d20082-90c3-431d-acd4-68b8f414e942"
          },
          {
            "name": "YE Forecast",
            "description": "Takes actual YTD and adds on forecast for future periods.",
            "expression": [
              "VAR _ActualYTD = [YTD Actual]",
              "",
              "VAR _ForecastYTD = [YTD Forecast]",
              "",
              "VAR _ForecastSimpleYE = ",
              "    CALCULATE (",
              "        [Forecast],",
              "        REMOVEFILTERS ( 'Calendar' ),",
              "        VALUES ( Calendar[Academic Year] )",
              "    )",
              "",
              "VAR _ForecastRemaining = _ForecastSimpleYE - _ForecastYTD",
              "",
              "VAR _ForecastYE = _ActualYTD + _ForecastRemaining",
              "",
              "VAR _Result = _ForecastYE",
              "",
              "RETURN _Result"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "40a89d1b-5823-469b-a30e-feff9aebfe2d"
          },
          {
            "name": "YE Variance",
            "expression": [
              "//VAR _DisplayMult = SELECTEDVALUE ( Nominal[Display Multiplier], -1)",
              "VAR _Result = ( [YE Budget] - [YE Forecast] )",
              "RETURN _Result"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Time Intelligence",
            "lineageTag": "3ddbae09-5313-4d26-909d-fed5b5f88079"
          },
          {
            "name": "YE Forecast Per Student",
            "expression": [
              "DIVIDE (",
              "    [YE Forecast],",
              "    [# Students]",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "CLFP",
            "lineageTag": "89fae120-43a8-4647-a8e9-f72b23d4b8f1"
          }
        ]
      },
      {
        "name": "XAccount",
        "lineageTag": "e0d61a74-d79b-421c-aa73-1950c2af1e4b",
        "columns": [
          {
            "name": "XAccount Code",
            "dataType": "string",
            "sourceColumn": "XAccount Code",
            "lineageTag": "524f1db1-6db6-440c-8f7f-e2d81d2b06f8",
            "summarizeBy": "none"
          },
          {
            "name": "XAccount Name",
            "dataType": "string",
            "sourceColumn": "XAccount Name",
            "lineageTag": "97e3dcec-307c-487f-8573-5f01825976ac",
            "summarizeBy": "none"
          },
          {
            "name": "XAccountId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "XAccountId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "d84a367f-16f8-4e6c-96cc-dc0215dd0e48",
            "summarizeBy": "none"
          },
          {
            "name": "XLedger Code",
            "dataType": "string",
            "sourceColumn": "XLedger Code",
            "lineageTag": "599a11a2-d943-4091-a452-d125c85c9315",
            "summarizeBy": "none"
          },
          {
            "name": "XLedger Name",
            "dataType": "string",
            "sourceColumn": "XLedger Name",
            "lineageTag": "cc18d00b-f82b-463f-8bb7-e98b2fe3ca4f",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "XAccount",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "    Nav = Source{[Schema = \"fin\", Item = \"Dim_XAccounts\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "UserGroupSecurity",
        "isHidden": true,
        "lineageTag": "e37f9af1-0f7c-4242-a4e6-8e37c36dc44d",
        "columns": [
          {
            "name": "SecurityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SecurityId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "231b1ec2-6834-43c7-a032-263bb58eb7dc",
            "summarizeBy": "none"
          },
          {
            "name": "UserGroupId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "UserGroupId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "5c667992-4d99-4956-bceb-94069626f340",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "UserGroupSecurity",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "    Nav = Source{[Schema = \"fin\", Item = \"Dim_UserGroupSecurity\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "User",
        "description": "RLS User Table. Security by default is set to not propagate. You need to add a page/report filter onto Email as \"Is Not Blank\" to turn RLS on.",
        "lineageTag": "8447e246-e0ca-4b4c-b9e1-efde20203fc3",
        "columns": [
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "8f3a48d1-5354-44f6-baa5-47924879ceb5"
          },
          {
            "name": "UserGroupId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "UserGroupId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "0041a47a-f1ee-4015-a3a7-fa0771c6af74"
          }
        ],
        "partitions": [
          {
            "name": "User",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "    Nav = Source{[Schema = \"fin\", Item = \"Dim_Users\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "Commitments",
        "lineageTag": "b10d0fba-bef8-4be9-98f6-f12014fd8126",
        "columns": [
          {
            "name": "AccountId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "47a9417c-3524-4a37-b743-0c34fc36f45d"
          },
          {
            "name": "AuditId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AuditId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "2d202477-ef01-42ee-b8b3-910f201d2c5e"
          },
          {
            "name": "NominalId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "6d3dccf5-485f-46f1-9e57-e7a3155bb63b"
          },
          {
            "name": "PeriodEndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "PeriodEndDate",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "acf6d067-a3d0-4958-94f3-b01b95d09da2"
          },
          {
            "name": "SecurityId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SecurityId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "fa92d351-0bd5-4e64-8447-c181a618bd14"
          },
          {
            "name": "Value",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Value",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "8e610176-577c-4520-aa91-4b01510c52fc"
          },
          {
            "name": "XAccountId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "XAccountId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "d970e85f-7780-4f02-afe3-04284863e23c"
          },
          {
            "name": "Commited",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Commited",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "df295fbf-61fa-45dc-8339-b22fbb152070"
          },
          {
            "name": "CommitmentDocumentId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CommitmentDocumentId",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "a1fceb54-c48c-4d54-ab8b-ef979d3990a1"
          },
          {
            "name": "AccountLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountLocationId",
            "lineageTag": "f4b964c7-b660-4341-9dcd-ad6cd27786cf"
          },
          {
            "name": "NominalLocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NominalLocationId",
            "lineageTag": "06777cb1-3c54-408e-9178-610b53e18f15"
          },
          {
            "name": "RefNo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RefNo",
            "lineageTag": "72450122-3c2f-47e4-8e75-8171e85d47d3"
          }
        ],
        "partitions": [
          {
            "name": "Commitments",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "    Nav = Source{[Schema = \"fin\", Item = \"Fact_Commitments\"]}[Data],",
                "    RemoveCol = Table.RemoveColumns(Nav, {\"FinancialPeriodId\"})",
                "in",
                "  RemoveCol"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Commitment",
            "description": "Includes GRN and POAUT.",
            "expression": [
              "SUMX(",
              "    Commitments,",
              "    Commitments[Value] * Commitments[Commited]",
              ")"
            ],
            "formatString": "#,##0.00; +#,##0.00",
            "lineageTag": "b3ab3e26-9d73-4440-9abe-b83febcc38e0"
          },
          {
            "name": "YTD Commitment",
            "expression": "CALCULATE( [Commitment], DATESYTD( Calendar[Date], \"31-Aug\" ) )",
            "formatString": "#,##0.00; +#,##0.00",
            "lineageTag": "c2230950-6a2a-456a-8c8d-920fc307b361"
          }
        ]
      },
      {
        "name": "Purchase Order Doc",
        "lineageTag": "f5fbb9ce-4e80-49e2-bf58-452764bf95d9",
        "columns": [
          {
            "name": "Commitment",
            "dataType": "string",
            "sourceColumn": "Commitment",
            "lineageTag": "0bcd0dc9-4563-428f-8702-3b7dfc50f62b"
          },
          {
            "name": "CommitmentDocumentId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CommitmentDocumentId",
            "lineageTag": "cbb4feb5-05bc-4a3f-849d-2527743fc901"
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "sourceColumn": "Document Date",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "f1b3dc3a-dcb9-4dfe-95da-58090ac2c174"
          },
          {
            "name": "Document Description",
            "dataType": "string",
            "sourceColumn": "Document Description",
            "lineageTag": "84429e2d-74b4-46e2-b8e0-7e8183431009"
          },
          {
            "name": "Document Number",
            "dataType": "int64",
            "sourceColumn": "Document Number",
            "lineageTag": "f3fd7088-28fc-4d33-966a-3013c90c2022"
          },
          {
            "name": "Document Status",
            "dataType": "string",
            "sourceColumn": "Document Status",
            "lineageTag": "8ff5c64b-c7ba-4fe9-8b91-b06b6ca51c54"
          },
          {
            "name": "Document Status Code",
            "dataType": "string",
            "sourceColumn": "Document Status Code",
            "lineageTag": "e3363bcb-72b3-4151-ba1e-d5920d3d8f01"
          },
          {
            "name": "Document Type Code",
            "dataType": "string",
            "sourceColumn": "Document Type Code",
            "lineageTag": "445039ce-608e-42ae-926e-4bb0a06d9720"
          }
        ],
        "partitions": [
          {
            "name": "Purchase Order Doc",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "    Nav = Source{[Schema = \"fin\", Item = \"Dim_CommitmentDocuments\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      },
      {
        "name": "Document Ages",
        "description": "Document age groups for those with a status code of Open or Disputed.",
        "lineageTag": "6e166d57-bee4-4509-8283-4f409bc3064b",
        "columns": [
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "sortByColumn": "AgedDocumentId",
            "lineageTag": "b22b48f6-19f3-4fd8-8776-285ddf2813a9"
          },
          {
            "name": "AgedDocumentId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AgedDocumentId",
            "lineageTag": "e9144cba-05e0-4f10-91cc-3b1fa5c1c6f5"
          },
          {
            "name": "MaximumDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MaximumDays",
            "lineageTag": "90dc0190-b228-41ec-a75f-c0721151adfc"
          },
          {
            "name": "MinimumDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MinimumDays",
            "lineageTag": "eb3aaded-45fc-4c05-b8f2-496957950cef"
          }
        ],
        "partitions": [
          {
            "name": "Document Ages",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\",\"ALT-DW\"),",
                "    Data = Source{[Schema=\"fin\",Item=\"Dim_AgedDocuments\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ]
      },
      {
        "name": "Display Formats (CG)",
        "lineageTag": "46a4d5b9-b2a7-4a91-beaa-5c4733d039ad",
        "calculationGroup": {
          "precedence": 10,
          "calculationItems": [
            {
              "name": "Raw PSF",
              "expression": "SELECTEDMEASURE()",
              "ordinal": 0
            },
            {
              "name": "Apply sign changes and show as 1000s",
              "expression": [
                "VAR _MeasureName = SELECTEDMEASURENAME()",
                "VAR _MeasureValue = SELECTEDMEASURE()",
                "",
                "VAR _Ignore = ",
                "        CALCULATE (",
                "            ISEMPTY ( 'Measure Details' ),",
                "            'Measure Details'[Measure Name] = _MeasureName,",
                "            'Measure Details'[Allow Sign Change]",
                "        )",
                "",
                "VAR _DisplayMultiplier = SELECTEDVALUE ( Nominal[Display Multiplier], -1 )",
                "",
                "VAR _Result = ",
                "    IF(",
                "        _Ignore,",
                "        _MeasureValue,",
                "        _MeasureValue * _DisplayMultiplier",
                "    )",
                "",
                "RETURN _Result"
              ],
              "ordinal": 4,
              "formatStringDefinition": {
                "expression": [
                  "VAR _MeasureName = SELECTEDMEASURENAME()",
                  "VAR _MeasureFormat = SELECTEDMEASUREFORMATSTRING()",
                  "",
                  "",
                  "VAR _Ignore = ",
                  "         CALCULATE (",
                  "            ISEMPTY ( 'Measure Details' ),",
                  "            'Measure Details'[Measure Name] = _MeasureName,",
                  "            'Measure Details'[Allow Scale Change]",
                  "        )",
                  "   ",
                  "VAR _CorrectMagnitude = ",
                  "    IF(",
                  "        _Ignore,",
                  "        _MeasureFormat,",
                  "        \"#,0,\"",
                  "    )",
                  "",
                  "RETURN _CorrectMagnitude"
                ]
              }
            },
            {
              "name": "Apply sign changes",
              "expression": [
                "VAR _MeasureName = SELECTEDMEASURENAME()",
                "VAR _MeasureValue = SELECTEDMEASURE()",
                "",
                "VAR _Ignore = ",
                "        CALCULATE (",
                "            ISEMPTY ( 'Measure Details' ),",
                "            'Measure Details'[Measure Name] = _MeasureName,",
                "            'Measure Details'[Allow Sign Change]",
                "        )                   ",
                "",
                "VAR _DisplayMultiplier = SELECTEDVALUE ( Nominal[Display Multiplier], -1 )",
                "",
                "VAR _Result = ",
                "    IF(",
                "        _Ignore,",
                "        _MeasureValue,",
                "        _MeasureValue * _DisplayMultiplier",
                "    )",
                "",
                "RETURN _Result"
              ],
              "ordinal": 3
            },
            {
              "name": "Invert PSF",
              "expression": [
                "VAR _MeasureName = SELECTEDMEASURENAME()",
                "VAR _MeasureValue = SELECTEDMEASURE()",
                "",
                "VAR _Ignore = ",
                "        CALCULATE (",
                "            ISEMPTY ( 'Measure Details' ),",
                "            'Measure Details'[Measure Name] = _MeasureName,",
                "            'Measure Details'[Allow Sign Change]",
                "        )",
                "                    ",
                "RETURN IF( _Ignore, _MeasureValue, _MeasureValue * -1)"
              ],
              "ordinal": 1
            },
            {
              "name": "Invert PSF and show as 1000s",
              "expression": [
                "VAR _MeasureName = SELECTEDMEASURENAME()",
                "VAR _MeasureValue = SELECTEDMEASURE()",
                "",
                "VAR _Ignore = ",
                "        CALCULATE (",
                "            ISEMPTY ( 'Measure Details' ),",
                "            'Measure Details'[Measure Name] = _MeasureName,",
                "            'Measure Details'[Allow Sign Change]",
                "        )",
                "                    ",
                "RETURN IF( _Ignore, _MeasureValue, _MeasureValue * -1)"
              ],
              "ordinal": 2,
              "formatStringDefinition": {
                "expression": [
                  "VAR _MeasureName = SELECTEDMEASURENAME()",
                  "VAR _MeasureFormat = SELECTEDMEASUREFORMATSTRING()",
                  "",
                  "",
                  "VAR _Ignore = ",
                  "         CALCULATE (",
                  "            ISEMPTY ( 'Measure Details' ),",
                  "            'Measure Details'[Measure Name] = _MeasureName,",
                  "            'Measure Details'[Allow Scale Change]",
                  "        )",
                  "   ",
                  "VAR _CorrectMagnitude = ",
                  "    IF(",
                  "        _Ignore,",
                  "        _MeasureFormat,",
                  "        \"#,0,\"",
                  "    )",
                  "",
                  "RETURN _CorrectMagnitude"
                ]
              }
            }
          ]
        },
        "columns": [
          {
            "name": "Display Format",
            "dataType": "string",
            "description": "Add this into the filter pane for the visual or page.",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Location (Nominal)",
        "lineageTag": "80a94f21-4c37-4397-be01-e5a2a8716a00",
        "columns": [
          {
            "name": "NominalLocationId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "SiteId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "13d2ac7d-214e-4dfb-a0ee-56013b181254",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Finance Code (Nominal)",
            "dataType": "string",
            "sourceColumn": "Finance Location Code",
            "lineageTag": "29104313-bd32-441a-baf7-672f4ff479df"
          },
          {
            "name": "Location Code (Nominal)",
            "dataType": "string",
            "sourceColumn": "Academy Code",
            "lineageTag": "cb4df5e8-f823-42da-80ea-2d55cb26d690"
          },
          {
            "name": "Location Name (Nominal)",
            "dataType": "string",
            "sourceColumn": "Site Name",
            "lineageTag": "99a90976-b090-4c1f-b6fb-9b0ef511f28e"
          }
        ],
        "partitions": [
          {
            "name": "Location (Nominal)",
            "mode": "import",
            "queryGroup": "Conformed",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source             = PowerPlatform.Dataflows ( null ), ",
                "  Workspaces         = Source{[ Id = \"Workspaces\" ]}[Data], ",
                "  Workspace          = Workspaces{[ workspaceName = \"DW-Dataflows-Conformed\" ]}[Data], ",
                "  Dataflow           = Workspace{[ dataflowName = \"Con-General\" ]}[Data], ",
                "  Entity             = Dataflow{[ entity = \"dimSites\", version = \"\" ]}[Data], ",
                "  FilteredRows       = Table.SelectRows (",
                "    Entity, ",
                "    each (",
                "      [Finance Location Code] <> \"Global\"",
                "    )",
                "  ), ",
                "  RemoveOtherColumns = Table.SelectColumns (",
                "    FilteredRows, ",
                "    { \"SiteId\", \"Finance Location Code\", \"Education Location Code\", \"Academy Code\", \"Site Name\" }",
                "  )",
                "in",
                "  RemoveOtherColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "Location (Account)",
        "lineageTag": "7ac1d370-83a4-446b-b79d-5b1f0477b166",
        "columns": [
          {
            "name": "AccountLocationId",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "sourceColumn": "SiteId",
            "formatString": "0",
            "isAvailableInMdx": false,
            "encodingHint": "value",
            "lineageTag": "4c0857b9-bf4d-4976-bee4-0d0cf376e235",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Location Name (Account)",
            "dataType": "string",
            "sourceColumn": "Site Name",
            "lineageTag": "64b21b6b-21e1-49d1-8de0-82be0f28f85a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Finance Code (Account)",
            "dataType": "string",
            "sourceColumn": "Finance Location Code",
            "lineageTag": "fee2c8fa-f700-410a-93df-1d93cd14d240"
          },
          {
            "name": "Location Code (Account)",
            "dataType": "string",
            "sourceColumn": "Academy Code",
            "lineageTag": "35b6f036-598b-49e9-8a42-6484de064849"
          }
        ],
        "partitions": [
          {
            "name": "Location (Account)",
            "mode": "import",
            "queryGroup": "Conformed",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  Source             = PowerPlatform.Dataflows ( null ), ",
                "  Workspaces         = Source{[ Id = \"Workspaces\" ]}[Data], ",
                "  Workspace          = Workspaces{[ workspaceName = \"DW-Dataflows-Conformed\" ]}[Data], ",
                "  Dataflow           = Workspace{[ dataflowName = \"Con-General\" ]}[Data], ",
                "  Entity             = Dataflow{[ entity = \"dimSites\", version = \"\" ]}[Data], ",
                "  FilteredRows       = Table.SelectRows (",
                "    Entity, ",
                "    each (",
                "      [Finance Location Code] <> \"Global\" ",
                "    )",
                "  ), ",
                "  RemoveOtherColumns = Table.SelectColumns (",
                "    FilteredRows, ",
                "    { \"SiteId\", \"Finance Location Code\", \"Education Location Code\", \"Academy Code\", \"Site Name\" }",
                "  )",
                "in",
                "  RemoveOtherColumns"
              ]
            }
          }
        ]
      },
      {
        "name": "Students",
        "lineageTag": "c94edd15-0279-4808-8387-f12ef03295e8",
        "columns": [
          {
            "name": "End of Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "End of Month",
            "lineageTag": "059c6ceb-a3be-4128-a4fc-cfce6c3305cc"
          },
          {
            "name": "LocationId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LocationId",
            "lineageTag": "f4bdf7a5-aeb3-4814-b511-9a6a4d8d7b42"
          },
          {
            "name": "NCYear",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "NCYear",
            "lineageTag": "52ba9734-1d06-42a9-8916-07e9bcae069e"
          },
          {
            "name": "Students",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Students",
            "lineageTag": "c9d07700-09f5-4ae1-a097-dced476bc8e7"
          }
        ],
        "partitions": [
          {
            "name": "Students",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "  AnalysisQuery = AnalysisServices.Database(",
                "    \"powerbi://api.powerbi.com/v1.0/myorg/DW-Models\", ",
                "    \"Education\", ",
                "    [",
                "      Query",
                "        = \"EVALUATE",
                "                VAR _InSIMS =",
                "                    TREATAS ( { 1 }, Student[In SIMS] )",
                "                VAR _Enrollment =",
                "                    TREATAS (",
                "                        { \"\"Single Registration\"\", \"\"Main - Dual Registration\"\" },",
                "                        Student[Enrollment Status]",
                "                    )",
                "                VAR _AM =",
                "                    TREATAS ( { 1 }, Attendance[AM] )",
                "",
                "                RETURN",
                "                    SUMMARIZECOLUMNS (",
                "                        Site[SiteId],",
                "                        'Calendar'[End of Month],",
                "                        Student[NC Year],",
                "                        _InSIMS,",
                "                        _Enrollment,",
                "                        \"\"Students\"\", [Number Of Students]",
                "                    )\", ",
                "      Implementation = \"2.0\"",
                "    ]",
                "  ), ",
                "  RenameCols = Table.RenameColumns(",
                "    AnalysisQuery, ",
                "    {",
                "      {\"Site[SiteId]\", \"LocationId\"}, ",
                "      {\"Calendar[End of Month]\", \"End of Month\"}, ",
                "      {\"Student[NC Year]\", \"NCYear\"}, ",
                "      {\"[Students]\", \"Students\"}",
                "    }",
                "  ), ",
                "  ChangeTypes = Table.TransformColumnTypes(",
                "    RenameCols, ",
                "    {{\"LocationId\", Int64.Type}, {\"End of Month\", type date}, {\"NCYear\", Int64.Type}, {\"Students\", Int64.Type}}",
                "  )",
                "in",
                "  ChangeTypes"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Students",
            "description": "Currently only a simple average. Needs hardening.",
            "expression": [
              "AVERAGEX (",
              "    VALUES( Calendar[End of Month] ),",
              "    CALCULATE ( SUM ( Students[Students] ) )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "87565cec-d1ef-44aa-b082-27885659546d"
          }
        ]
      },
      {
        "name": "Measure Details",
        "description": "Table containing measure meta data.",
        "isHidden": true,
        "lineageTag": "d2b716af-bda4-4f21-84ed-788c0207e2b2",
        "columns": [
          {
            "name": "Allow Scale Change",
            "dataType": "boolean",
            "sourceColumn": "Allow Scale Change",
            "lineageTag": "dfe07ead-f91e-4ee3-94fa-044bb40a79b9"
          },
          {
            "name": "Allow Sign Change",
            "dataType": "boolean",
            "sourceColumn": "Allow Sign Change",
            "lineageTag": "da61948e-92b5-4921-b11f-88b4f7658d44"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "f7d19e6d-08b1-4e57-9a04-9dad950ad759"
          },
          {
            "name": "Measure Name",
            "dataType": "string",
            "sourceColumn": "Measure Name",
            "lineageTag": "b163ca34-9017-4c4a-8620-390d496f885e"
          },
          {
            "name": "Measure Table",
            "dataType": "string",
            "sourceColumn": "Measure Table",
            "lineageTag": "b2b198a3-2658-45d0-a3ef-8a2ff640b707"
          }
        ],
        "partitions": [
          {
            "name": "Measure Details",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"core-sys-dw01\", \"ALT-DW\"),",
                "    Nav = Source{[Schema = \"fin\", Item = \"Helper_Measures\"]}[Data]",
                "in",
                "  Nav"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "3a39f735-1039-4b91-92d5-8449761c10ab",
        "fromTable": "Budgets",
        "fromColumn": "AccountId",
        "toTable": "Account",
        "toColumn": "AccountId"
      },
      {
        "name": "4377041a-d951-4e41-b5b3-cd9ef0342d92",
        "fromTable": "Actuals",
        "fromColumn": "AccountId",
        "toTable": "Account",
        "toColumn": "AccountId"
      },
      {
        "name": "50469c37-59f3-4937-923f-6df39b25ad6c",
        "fromTable": "Budgets",
        "fromColumn": "NominalId",
        "toTable": "Nominal",
        "toColumn": "NominalId"
      },
      {
        "name": "5172aed4-2546-4e5e-b9ae-45164435282b",
        "fromTable": "Actuals",
        "fromColumn": "NominalId",
        "toTable": "Nominal",
        "toColumn": "NominalId"
      },
      {
        "name": "17f32684-3550-41ff-96be-7ec260fe6172",
        "fromTable": "Budgets",
        "fromColumn": "AuditId",
        "toTable": "Audit",
        "toColumn": "AuditId"
      },
      {
        "name": "be6c1b81-c554-4cfe-9377-5106a2ef1e34",
        "fromTable": "Budgets",
        "fromColumn": "BudgetNameId",
        "toTable": "Budget Name",
        "toColumn": "BudgetNameId"
      },
      {
        "name": "878bcc13-ea07-4cc8-be6c-b28044bd29ff",
        "fromTable": "Actuals",
        "fromColumn": "AuditId",
        "toTable": "Audit",
        "toColumn": "AuditId"
      },
      {
        "name": "4a351503-f6fb-4017-bd5c-22d7b9d8b7cb",
        "fromTable": "PSF User",
        "fromColumn": "Latest PSF Use",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "48c29ade-8303-4cfe-bfae-136044298cd9",
        "fromTable": "Actuals",
        "fromColumn": "DocumentId",
        "toTable": "Document",
        "toColumn": "DocumentId"
      },
      {
        "name": "a66f495b-134a-4b2c-9165-f59566813e5e",
        "fromTable": "Actuals",
        "fromColumn": "ActualDescriptionId",
        "toTable": "Actual Description",
        "toColumn": "ActualDescriptionId"
      },
      {
        "name": "b4830e2c-77d2-4151-9fc4-b76fd4c5b68f",
        "fromTable": "Forecasts",
        "fromColumn": "AuditId",
        "toTable": "Audit",
        "toColumn": "AuditId"
      },
      {
        "name": "e133ad95-9ed1-4b3d-baf7-8f29262119de",
        "fromTable": "Forecasts",
        "fromColumn": "AccountId",
        "toTable": "Account",
        "toColumn": "AccountId"
      },
      {
        "name": "b0559e5c-ae92-46a7-a4b8-d913e180d359",
        "fromTable": "Forecasts",
        "fromColumn": "NominalId",
        "toTable": "Nominal",
        "toColumn": "NominalId"
      },
      {
        "name": "aecbbda1-c0ec-41ea-a9f4-ff1834fb0a06",
        "fromTable": "Forecasts",
        "fromColumn": "ForcastNameId",
        "toTable": "Forecast Name",
        "toColumn": "ForecastNameId"
      },
      {
        "name": "ac0b1ace-3930-4d67-ab5a-f86fdbf37f0f",
        "fromTable": "Forecasts",
        "fromColumn": "Period End Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "1aba1d0a-c31d-4350-9c6b-ee3f650998b4",
        "fromTable": "Actuals",
        "fromColumn": "PeriodEndDate",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "95d6b2ef-8f4d-4cb3-a2a9-1e1e7fd455ec",
        "fromTable": "Budgets",
        "fromColumn": "Period End Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "4046155f-bfb2-435e-8892-b85a9fb8fc41",
        "fromTable": "Actuals",
        "fromColumn": "XAccountId",
        "toTable": "XAccount",
        "toColumn": "XAccountId"
      },
      {
        "name": "873ef171-affb-4658-a0a8-85b892e9a59e",
        "toCardinality": "many",
        "fromTable": "Actuals",
        "fromColumn": "SecurityId",
        "toTable": "UserGroupSecurity",
        "toColumn": "SecurityId"
      },
      {
        "name": "4a83e017-f2d8-4bad-90ff-d5b7653485ad",
        "toCardinality": "many",
        "fromTable": "UserGroupSecurity",
        "fromColumn": "UserGroupId",
        "toTable": "User",
        "toColumn": "UserGroupId",
        "securityFilteringBehavior": "none"
      },
      {
        "name": "44ff0929-5880-411f-b889-b8a112e16243",
        "toCardinality": "many",
        "fromTable": "Budgets",
        "fromColumn": "SecurityId",
        "toTable": "UserGroupSecurity",
        "toColumn": "SecurityId"
      },
      {
        "name": "673ede1b-cfba-4b2f-a970-2949901da271",
        "toCardinality": "many",
        "fromTable": "Forecasts",
        "fromColumn": "SecurityId",
        "toTable": "UserGroupSecurity",
        "toColumn": "SecurityId"
      },
      {
        "name": "c1da00d8-8c98-47a8-b890-509302e40b61",
        "fromTable": "Commitments",
        "fromColumn": "AccountId",
        "toTable": "Account",
        "toColumn": "AccountId"
      },
      {
        "name": "df1c227d-2d5b-4c0a-964d-947ebfc2dd89",
        "fromTable": "Commitments",
        "fromColumn": "CommitmentDocumentId",
        "toTable": "Purchase Order Doc",
        "toColumn": "CommitmentDocumentId"
      },
      {
        "name": "3f8ea753-1002-4d1e-9a54-c7234f751152",
        "fromTable": "Commitments",
        "fromColumn": "NominalId",
        "toTable": "Nominal",
        "toColumn": "NominalId"
      },
      {
        "name": "ebf3b51b-af85-4cdd-a2da-2515de99943a",
        "fromTable": "Commitments",
        "fromColumn": "PeriodEndDate",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "4d8ba200-99e9-4b5a-8623-6f0ad2f6cc28",
        "toCardinality": "many",
        "fromTable": "Commitments",
        "fromColumn": "SecurityId",
        "toTable": "UserGroupSecurity",
        "toColumn": "SecurityId"
      },
      {
        "name": "bb972c9b-bb11-41d8-8366-3b1934a8b0dc",
        "fromTable": "Actuals",
        "fromColumn": "AgedDocumentId",
        "toTable": "Document Ages",
        "toColumn": "AgedDocumentId"
      },
      {
        "name": "af40b400-7dce-4e87-9073-60ec9fce509a",
        "fromTable": "Actuals",
        "fromColumn": "AccountLocationId",
        "toTable": "Location (Account)",
        "toColumn": "AccountLocationId"
      },
      {
        "name": "0660dd54-0e51-48fd-966f-6ed02bceb13e",
        "fromTable": "Budgets",
        "fromColumn": "AccountLocationId",
        "toTable": "Location (Account)",
        "toColumn": "AccountLocationId"
      },
      {
        "name": "4de77476-a333-491b-9ef4-9db6e6245f73",
        "fromTable": "Forecasts",
        "fromColumn": "AccountLocationId",
        "toTable": "Location (Account)",
        "toColumn": "AccountLocationId"
      },
      {
        "name": "14db36f9-e0eb-48e1-8e86-51852a3565c8",
        "fromTable": "Commitments",
        "fromColumn": "AccountLocationId",
        "toTable": "Location (Account)",
        "toColumn": "AccountLocationId"
      },
      {
        "name": "8462f4ac-07c9-41e7-bb5d-fb3615645c4f",
        "fromTable": "Actuals",
        "fromColumn": "NominalLocationId",
        "toTable": "Location (Nominal)",
        "toColumn": "NominalLocationId"
      },
      {
        "name": "6d1f6510-c9bf-4690-88dd-63b50c0daea3",
        "fromTable": "Budgets",
        "fromColumn": "NominalLocationId",
        "toTable": "Location (Nominal)",
        "toColumn": "NominalLocationId"
      },
      {
        "name": "6f4e360b-8c3d-407c-8e22-4453db12a8d6",
        "fromTable": "Forecasts",
        "fromColumn": "NominalLocationId",
        "toTable": "Location (Nominal)",
        "toColumn": "NominalLocationId"
      },
      {
        "name": "f720d1ca-8dbe-4226-92d0-656244eb7091",
        "fromTable": "Commitments",
        "fromColumn": "NominalLocationId",
        "toTable": "Location (Nominal)",
        "toColumn": "NominalLocationId"
      },
      {
        "name": "bc9c8528-c982-484d-aaed-20b02ca7e7ea",
        "toCardinality": "many",
        "fromTable": "Students",
        "fromColumn": "End of Month",
        "toTable": "Calendar",
        "toColumn": "End of Month"
      },
      {
        "name": "2ab36c91-02ba-485e-8349-0224f221e65f",
        "fromTable": "Students",
        "fromColumn": "LocationId",
        "toTable": "Location (Account)",
        "toColumn": "AccountLocationId"
      },
      {
        "name": "f32dff94-8263-426a-ba3e-62ddd918ef8c",
        "fromTable": "Students",
        "fromColumn": "LocationId",
        "toTable": "Location (Nominal)",
        "toColumn": "NominalLocationId"
      }
    ],
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-GB",
            "DynamicImprovement": "HighConfidence"
          },
          "contentType": "json"
        }
      }
    ],
    "roles": [
      {
        "name": "Everything",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "obj:2489bb71-8bda-476b-b035-a5a74e5adcb5@23990c89-ae67-4afc-87ce-470c97afeb37",
            "memberId": "2489bb71-8bda-476b-b035-a5a74e5adcb5",
            "identityProvider": "AzureAD",
            "memberType": "group"
          }
        ]
      },
      {
        "name": "DynamicPSF",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "JBU@emmanuel.nottingham.sch.uk",
            "memberId": "00ee3d9e-4c58-4e1f-8ddd-2cce1832a63a",
            "identityProvider": "AzureAD",
            "memberType": "user"
          }
        ],
        "tablePermissions": [
          {
            "name": "User",
            "filterExpression": "User[Email] = USERPRINCIPALNAME()"
          }
        ]
      }
    ],
    "extendedProperties": [
      {
        "type": "json",
        "name": "TabularEditor_DeploymentMetadata",
        "value": {
          "User": "BCA\\bdobbs",
          "Time": "2023-02-20T14:46:35.536326+00:00",
          "ClientMachine": "ALT-LAP-S44831",
          "DeploymentMode": "SaveUI",
          "TabularEditorBuild": "3.4.8440.26878"
        }
      }
    ],
    "queryGroups": [
      {
        "folder": "Conformed",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Finance",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Finance\\Dimensions",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Finance\\Facts",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "BestPracticeAnalyzer_IgnoreRules",
        "value": "{\"RuleIDs\":[]}"
      },
      {
        "name": "BestPracticeAnalyzer_ExternalRuleFiles",
        "value": "[\"C:\\\\Users\\\\bdobbs\\\\Downloads\\\\BPARules-standard.json\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":true,\"LocalPerspectives\":true,\"LocalRelationships\":true,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}