VAR _ActualYTD = [YTD Actual]

VAR _ForecastYTD = [YTD Forecast]

VAR _ForecastSimpleYE = 
    CALCULATE (
        [Forecast],
        REMOVEFILTERS ( 'Calendar' ),
        VALUES ( Calendar[Academic Year] )
    )

VAR _ForecastRemaining = _ForecastSimpleYE - _ForecastYTD

VAR _ForecastYE = _ActualYTD + _ForecastRemaining

VAR _Result = _ForecastYE

RETURN _Result