//VAR _DisplayMult = SELECTEDVALUE ( Nominal[Display Multiplier], -1)
VAR _Forecast = SUM( Forecasts[Value] ) 
VAR _ForecastDisplay =
    IF(
        ISFILTERED( 'Actual Description' ) || ISFILTERED ( XAccount ),
        BLANK( ),
        _Forecast
    )
VAR _Result = _ForecastDisplay
RETURN
    _Result