VAR _tblDocs = 
CALCULATETABLE(
    SUMMARIZE(
        Actuals,
        Actuals[DocumentId],
        Actuals[GRNDocDate],
        Actuals[DocumentDate]
    ),
    NOT ( ISBLANK( Actuals[GRNDocDate] ) )
)

VAR _NumDocs = COUNTROWS ( _tblDocs )
VAR _NumLate = 
    COUNTROWS(
        FILTER(
            _tblDocs,
            Actuals[GRNDocDate] - Actuals[DocumentDate] > 10
        )
    )
    
VAR _Result = DIVIDE (_NumLate, _NumDocs)

RETURN _Result